### ISSUE TITLE
Error MSB6006 "cmd.exe" exited with code 1

### ISSUE THREAD

**Issue by 2H0U** [nvpro-samples/optix_prime_baking#4]
**I followed the instructions described at https://github.com/nvpro-samples/optix_prime_baking, but there is a problem in building the optix_prime_baking project using vs2015. The optix_advanced_samples project has no such problem. Need help, thanks in advance. Here is some  building output:**

=============================================================
nvcc fatal   : Stray '"' character
3>    CMake Error at optix_prime_baking_generated_bake_kernels.cu.obj.Debug.cmake:222 (message):
3>      Error generating
3>      D:/Code/nvpro-samples/build_all/build/optix_prime_baking/CMakeFiles/optix_prime_baking.dir//Debug/optix_prime_baking_generated_bake_kernels.cu.obj
3>
3>
3>    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.

**Comment by 2H0U** [comment]
The problem is caused by cmake 3.9.1, and returning to 3.6 can solve it.

**Comment by ivalylo** [comment]
3.10 is the same thing... And 3.6 doesn't support 2017. IMO, this should be reopened...
